-- ============================================================
-- Query pipeline: nested subqueries chain filters, then project.
-- ============================================================
--
-- Templates (2 generic filters + 1 projection):
--   filter_set.sql         Generic set membership (IN / NOT IN)
--   filter_substring.sql   Generic substring match (LIKE / NOT LIKE)
--   projection.sql         Final column selection + ordering
--
-- Each filter wraps the current inner query:
--   SELECT * FROM ({inner}) WHERE {condition}
--
-- Pipeline example (level=A, conf=ICML,NeurIPS, year=2024,
--                    title contains "diffusion", excludes "survey"):
--
--   -- 1. Title include (filter_substring.sql)
--   SELECT * FROM papers
--   WHERE LOWER(title) LIKE '%diffusion%'
--
--   -- 2. Title exclude (filter_substring.sql)
--   SELECT * FROM (...) WHERE LOWER(title) NOT LIKE '%survey%'
--
--   -- 3. Level include (filter_set.sql)
--   SELECT * FROM (...) WHERE LOWER(level) IN (?1)
--
--   -- 4. Conference include (filter_set.sql)
--   SELECT * FROM (...) WHERE LOWER(conference) IN (?2,?3)
--
--   -- 5. Year include (filter_set.sql)
--   SELECT * FROM (...) WHERE year IN (?4)
--
--   -- 6. Projection (projection.sql)
--   SELECT conference, year, title FROM (...) ORDER BY year DESC
--
-- Filters are applied in fixed order: title → level → conference → year.
-- Within each dimension, include is applied before exclude.
SELECT {columns}
FROM ({inner})
{order}
